// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SavvyfixAspNet.Data;

#nullable disable

namespace SavvyfixAspNet.Data.Migrations
{
    [DbContext(typeof(SavvyfixMetadataDbContext))]
    partial class SavvyfixMetadataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Atividades", b =>
                {
                    b.Property<long>("IdAtividades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAtividades"));

                    b.Property<string>("ClimaAtual")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DemandaProduto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("HorarioAtual")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("IdCliente")
                        .IsRequired()
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("LocalizacaoAtual")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PrecoVariado")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("QntdProcura")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdAtividades");

                    b.HasIndex("IdCliente");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("CpfClie")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<long?>("IdEndereco")
                        .IsRequired()
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmClie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SenhaClie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Compra", b =>
                {
                    b.Property<long>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCompra"));

                    b.Property<string>("EspcificacoesProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("IdAtividades")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("IdCliente")
                        .IsRequired()
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("IdProd")
                        .IsRequired()
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QntdProd")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdAtividades");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProd");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Endereco", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEndereco"));

                    b.Property<string>("BairroEndeereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EstadoEndereco")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.Property<string>("NumEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PaisEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RuaEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEndereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Produto", b =>
                {
                    b.Property<long>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProd"));

                    b.Property<string>("DescProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MarcaProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PrecoFixo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdProd");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Atividades", b =>
                {
                    b.HasOne("SavvyfixAspNet.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Atividades")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("SavvyfixAspNet.Domain.Entities.Endereco", "Endereco")
                        .WithMany("Clientes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Compra", b =>
                {
                    b.HasOne("SavvyfixAspNet.Domain.Entities.Atividades", "Atividades")
                        .WithMany("Compras")
                        .HasForeignKey("IdAtividades");

                    b.HasOne("SavvyfixAspNet.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Compras")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavvyfixAspNet.Domain.Entities.Produto", "Produto")
                        .WithMany("Compras")
                        .HasForeignKey("IdProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividades");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Atividades", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Compras");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Endereco", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SavvyfixAspNet.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
